### PR TITLE
Support for multple functionalities per device

### LINKED ISSUE #12: Only first type of a device is added
If multiple functionalities are supported by a device only the first match is added to HA + Sensors if applicable.

### PR DESCRIPTION
**Pull request by JonasR-M**
Devices may support multiple functionalites, don't stop adding after first match.
Closes #12

### CODE REVIEW

**Review by jsloth — DISMISSED** [review]
By doing this you will get multiple Light from same endpoint. One for ColorControl and one for Level. In addition you will get a binary switch for your lights as well in addition to Light.

**Comment by JonasR-M** [comment]
True, so we should group it into valid combinations. Mainly its Light that has collisions as I see it.

**Comment by JonasR-M** [comment]
Some switches have light support, e.g. LED ring. So I think we would need to accept having OnOff for a light, that or no Light for a Switch with LED indication?

**Comment by jsloth** [comment]
> Some switches have light support, e.g. LED ring. So I think we would need to accept having OnOff for a light, that or no Light for a Switch with LED indication?

If the devices were made properly they should have 1 endpoint for the led and 1 for the switch. This is quirk handling imo.
I would be annoyed that all my lights have a duplicate binary switch device.

**Comment by JonasR-M** [comment]
LogicGroup Matrix Relay have both OnOff + ColorControl on endpoints 1-4 (OnOff controls the LED if i recall), and OnOff only on endpoints 5-6 (for relays), if we ignore OnOff on 1-4 here, its not possible to turn on and off the LED?
In addition single endpoint devices that does this also exist, I have multiple.

**Comment by JonasR-M** [comment]
Ok, if we nest OnOff in Light device it will work for devices that conforms to this (like LogicGroups). But single endpoint devices would need special handling in Unify then.

**Comment by jsloth** [comment]
> Ok, if we nest OnOff in Light device it will work for devices that conforms to this (like LogicGroups). But single endpoint devices would need special handling in Unify then.

Yes, this is already done in UnifyLightEntity. On my Matrix I have OnOff, Level, and Color on ep1-4, and OnOff and Level on ep5. 

I think the "special" devices should be fixed on the ZPC. If you recall we have discussed making a quirk where we make virtual endpoints for such a device, so the OnOff will be provided on ep1 and Led on ep2.

**Comment by jsloth** [comment]
Just get it in, I'll take a look at how it looks in my setup and come up with a suggestion to fix it :)

**Review by jsloth — APPROVED** [review]

**Pull request merged**
